from typing import List
from .models import Product

PRODUCTS: List[Product] = [
    {
        "id": 1,
        "name": "Camisa Azul",
        "price": 29.99,
        "image": "assets/shirt-blue.png",
        "description": "Camisa de algodón, corte clásico, ideal para uso diario o formal.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "camisas",
    },
    {
        "id": 2,
        "name": "Pantalón Negro",
        "price": 49.99,
        "image": "assets/pants-black.png",
        "description": "Pantalón negro de vestir, cómodo y elegante.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "pantalones",
    },
    {
        "id": 3,
        "name": "Gorra",
        "price": 15.00,
        "image": "assets/cap.png",
        "description": "Gorra urbana ajustable, ideal para uso diario.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 4,
        "name": "Zapatos Deportivos",
        "price": 79.99,
        "image": "assets/shoes-sports.png",
        "description": "Zapatillas deportivas con amortiguación y suela antideslizante.",
        "sizes": ["38", "39", "40", "41", "42", "43"],
        "category": "calzado",
    },
    {
        "id": 5,
        "name": "Buzo Gris",
        "price": 39.99,
        "image": "assets/hoodie-gray.png",
        "description": "Buzo de algodón frisado, cómodo y abrigado.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "buzos",
    },
    {
        "id": 6,
        "name": "Remera Blanca",
        "price": 19.99,
        "image": "assets/tshirt-white.png",
        "description": "Remera básica blanca, algodón premium.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "remeras",
    },
    {
        "id": 7,
        "name": "Campera Negra",
        "price": 89.99,
        "image": "assets/jacket-black.png",
        "description": "Campera impermeable con cierre reforzado.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "camperas",
    },
    {
        "id": 8,
        "name": "Short Deportivo",
        "price": 24.99,
        "image": "assets/short-sport.png",
        "description": "Short liviano, ideal para entrenamientos.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "shorts",
    },
    {
        "id": 9,
        "name": "Mochila Urbana",
        "price": 59.99,
        "image": "assets/backpack.png",
        "description": "Mochila resistente con múltiples compartimentos.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 10,
        "name": "Reloj Digital",
        "price": 45.00,
        "image": "assets/watch-digital.png",
        "description": "Reloj digital resistente al agua.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 11,
        "name": "Medias Deportivas",
        "price": 9.99,
        "image": "assets/socks-sport.png",
        "description": "Medias deportivas respirables.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 12,
        "name": "Cinturón de Cuero",
        "price": 22.50,
        "image": "assets/belt-leather.png",
        "description": "Cinturón de cuero genuino.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 13,
        "name": "Lentes de Sol",
        "price": 34.99,
        "image": "assets/sunglasses.png",
        "description": "Lentes UV400 con marco liviano.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 14,
        "name": "Camisa Blanca",
        "price": 31.99,
        "image": "assets/shirt-white.png",
        "description": "Camisa blanca clásica, versátil y elegante.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "camisas",
    },
    {
        "id": 15,
        "name": "Jean Azul",
        "price": 54.99,
        "image": "assets/jeans-blue.png",
        "description": "Jean azul clásico de corte recto.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "pantalones",
    },
    {
        "id": 16,
        "name": "Zapatillas Urbanas",
        "price": 74.99,
        "image": "assets/sneakers-urban.png",
        "description": "Zapatillas urbanas cómodas para uso diario.",
        "sizes": ["38", "39", "40", "41", "42", "43"],
        "category": "calzado",
    },
    {
        "id": 17,
        "name": "Bufanda",
        "price": 18.00,
        "image": "assets/scarf.png",
        "description": "Bufanda de lana suave y abrigada.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 18,
        "name": "Gorro de Lana",
        "price": 14.50,
        "image": "assets/beanie.png",
        "description": "Gorro tejido, ideal para invierno.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
    {
        "id": 19,
        "name": "Campera Denim",
        "price": 92.00,
        "image": "assets/jacket-denim.png",
        "description": "Campera de jean clásica.",
        "sizes": ["S", "M", "L", "XL"],
        "category": "camperas",
    },
    {
        "id": 20,
        "name": "Bolso Deportivo",
        "price": 64.99,
        "image": "assets/sport-bag.png",
        "description": "Bolso amplio para entrenamiento o viajes cortos.",
        "sizes": ["Único"],
        "category": "accesorios",
    },
]
